### ISSUE TITLE
Lời gợi ý về cách học algorithm mà mình tìm hiểu được

### ISSUE THREAD

**Issue by mnguyen081002** [hi02102002/leet-code#1]
### Lướt github thì thấy Huy có tạo repo này, không biết là Huy đã có lộ trình chưa nên Nguyên chia sẻ một vài tìm hiểu của mình.

Dựa theo [video](https://www.youtube.com/watch?v=H16auN3wNIk&t=3366s) này, đây là một video của một nhóm các anh đã làm ở BigTech chia sẻ về cách học Algorithm (Nguyên đang theo học 1 khóa System Design ở đây với giá khá chát :( ).
Tóm tắt video thì các anh khuyên nên học theo topic và priority dựa trên trang [https://www.techinterviewhandbook.org/coding-interview-study-plan/](https://www.techinterviewhandbook.org/coding-interview-study-plan/) 

Trong group của mấy anh này có bạn sinh viên năm 3 theo 1 năm vừa đậu intern Coinbase 7k$ chỉ cần eng và algorithm mà nhủi lòng ...
 
![image](https://github.com/hi02102002/leet-code/assets/76799726/3c2e2fc8-89b0-4669-bbc7-2b52fa42a134)
![image](https://github.com/hi02102002/leet-code/assets/76799726/1faae8f3-0fe0-4a71-a742-cbd872d0149c)

**Comment by hi02102002** [comment]
Cảm ơn ông nhiều nha :v Tui cũng đang học lại dsa ắ. Cũng hay coi kênh này nữa mà chưa coi cái video ông gởi. Cảm ơn nhiều nha
